site_name: recipe-scrapers
site_url: https://docs.recipe-scrapers.com
site_description: Documentation for recipe-scrapers - Python package for scraping recipes data from the web
repo_url: https://github.com/hhursev/recipe-scrapers
repo_name: hhursev/recipe-scrapers

theme:
  name: material
  palette:
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Supported Sites: supported-sites.md
  - Contributing:
    - Contributing to Our Documentation: contributing-to-our-documentation.md
    - Overview: contributing.md
    - "In Depth: HTML Scraping": in-depth-guide-html-scraping.md
    - "In Depth: Scraper Functions": in-depth-guide-scraper-functions.md
    - "In Depth: Ingredient Groups": in-depth-guide-ingredient-groups.md
    - "In Depth: Debugging": in-depth-guide-debugging.md
  - API Reference:
    - Base Scraper: api/scraper.md
    - Exceptions: api/exceptions.md
    - Utils: api/utils.md

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables

plugins:
  - search
  - markdown-exec  # used in supported-sites.md
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: recipe_scrapers
          options:
            show_source: true
            show_root_heading: true
            heading_level: 1
            show_category_heading: true
            docstring_style: google
#            show_signature_annotations: true
#            show_if_no_docstring: true
#            show_root_full_path: true
#            members: true
#            show_private_members: true
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/hhursev/recipe-scrapers
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/recipe-scrapers/
