from recipe_scrapers.tests.test_allrecipes import *
from recipe_scrapers.tests.test_allrecipes_fallback_format import *
from recipe_scrapers.tests.test_bbcfood import *
from recipe_scrapers.tests.test_bbcgoodfood import *
from recipe_scrapers.tests.test_bettycrocker import *
from recipe_scrapers.tests.test_bonappetit import *
from recipe_scrapers.tests.test_budgetbytes import *
from recipe_scrapers.tests.test_closetcooking import *
from recipe_scrapers.tests.test_cookstr import *
from recipe_scrapers.tests.test_copykat import *
from recipe_scrapers.tests.test_cybercook import *
from recipe_scrapers.tests.test_epicurious import *
from recipe_scrapers.tests.test_delish import *
from recipe_scrapers.tests.test_finedininglovers import *
from recipe_scrapers.tests.test_food import *
from recipe_scrapers.tests.test_foodnetwork import *
from recipe_scrapers.tests.test_foodrepublic import *
from recipe_scrapers.tests.test_giallozafferano import *
from recipe_scrapers.tests.test_gonnawantseconds import *
from recipe_scrapers.tests.test_greatbritishchefs import *
from recipe_scrapers.tests.test_heinzbrasil import *
from recipe_scrapers.tests.test_hellofresh import *
from recipe_scrapers.tests.test_hundredandonecookbooks import *
from recipe_scrapers.tests.test_ig import *
from recipe_scrapers.tests.test_inspiralized import *
from recipe_scrapers.tests.test_jamieoliver import *
from recipe_scrapers.tests.test_justbento import *
from recipe_scrapers.tests.test_kitchn import *
from recipe_scrapers.tests.test_marmiton import *
from recipe_scrapers.tests.test_matprat import *
from recipe_scrapers.tests.test_mindmegette import *
from recipe_scrapers.tests.test_misya import *
from recipe_scrapers.tests.test_mybakingaddiction import *
from recipe_scrapers.tests.test_nihhealthyeating import *
from recipe_scrapers.tests.test_panelinha import *
from recipe_scrapers.tests.test_paninihappy import *
from recipe_scrapers.tests.test_przepisy import *
from recipe_scrapers.tests.test_realsimple import *
from recipe_scrapers.tests.test_seriouseats import *
from recipe_scrapers.tests.test_simplyrecipes import *
from recipe_scrapers.tests.test_southernliving import *
from recipe_scrapers.tests.test_steamykitchen import *
from recipe_scrapers.tests.test_tastesoflizzyt import *
from recipe_scrapers.tests.test_tastykitchen import *
from recipe_scrapers.tests.test_thepioneerwoman import *
from recipe_scrapers.tests.test_thespruceeats import *
from recipe_scrapers.tests.test_thehappyfoodie import *
from recipe_scrapers.tests.test_thevintagemixer import *
from recipe_scrapers.tests.test_tineno import *
from recipe_scrapers.tests.test_tudogostoso import *
from recipe_scrapers.tests.test_twopeasandtheirpod import *
from recipe_scrapers.tests.test_whatsgabycooking import *
from recipe_scrapers.tests.test_wikicookbook import *
from recipe_scrapers.tests.test_yummly import *
from recipe_scrapers.tests.test_geniuskitchen import *

import unittest


if __name__ == '__main__':
    unittest.main()
