name: coverage

on:
  push:
    branches: [ main, v14 ]
  pull_request:
    branches: [ main, v14 ]
    types: [ opened, synchronize, reopened ]

jobs:
  coverage:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache: pip
      - name: Install test packages
        run: pip install ".[tests]"
      - name: Run tests with coverage
        env:
          PYTHONWARNINGS: "always:::recipe_scrapers,ignore:::recipe_scrapers.plugins.static_values"
        run: coverage run -m unittest
      - name: Report coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
