name: coverage

on:
  push:
    branches:
      - main
      - v14
  pull_request:
    branches:
      - main
      - v14

jobs:
  coverage:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install coverage
        run: |
          pip install coverage
      - name: Run tests with coverage
        run: |
          coverage run -m unittest
      - name: Report coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
