name: timetravel

on:
  push:
    branches:
      - main
  # todo: should this run on every pull request?
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install tox
      - run: export SOURCE_DATE_EPOCH=$(date +%s)
      - run: tox -e ${{ matrix.toxenv }}
